name: Monitor first_last_agg Releases

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.check.outputs.new-version }}
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
      - uses: actions/checkout@v5
      - name: Fetch git tags
        run: git fetch --prune --unshallow --tags
      
      - name: Check for new first_last_agg release
        id: check
        run: |
          # Get latest release from GitHub API
          LATEST=$(curl -fsS https://api.github.com/repos/wulczer/first_last_agg/tags | jq -r '.[0].name')
          
          # Check if we already built this version
          if git tag | grep -q "first_last_agg-${LATEST}"; then
            echo "Version ${LATEST} already built"
            echo "should-build=false" >> $GITHUB_OUTPUT
          else
            echo "New version found: ${LATEST}"
            echo "new-version=${LATEST}" >> $GITHUB_OUTPUT
            echo "should-build=true" >> $GITHUB_OUTPUT
          fi

  build-and-test:
    needs: check-release
    if: needs.check-release.outputs.should-build == 'true'
    uses: ./.github/workflows/build-first_last_agg.yml
    with:
      first_last_agg-version: ${{ needs.check-release.outputs.new-version }}
    secrets: inherit
